package com.jxjr.ynzw.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-22T17:29:53.110+08:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "EntraceImpService",
                  wsdlLocation = "http://127.0.0.1:8787/Entrance?wsdl",
                  targetNamespace = "http://app.ynzw.jxjr.com/")
public class EntraceImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://app.ynzw.jxjr.com/", "EntraceImpService");
    public final static QName EntraceImpPort = new QName("http://app.ynzw.jxjr.com/", "EntraceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8787/Entrance?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EntraceImpService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8787/Entrance?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EntraceImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EntraceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntraceImpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EntraceImpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EntraceImpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EntraceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Entrance
     */
    @WebEndpoint(name = "EntraceImpPort")
    public Entrance getEntraceImpPort() {
        return super.getPort(EntraceImpPort, Entrance.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Entrance
     */
    @WebEndpoint(name = "EntraceImpPort")
    public Entrance getEntraceImpPort(WebServiceFeature... features) {
        return super.getPort(EntraceImpPort, Entrance.class, features);
    }

}
