package com.jxjr.ynzw.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-22T17:29:53.035+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://127.0.0.1:8787/Entrance", name = "Entrance")
@XmlSeeAlso({ObjectFactory.class})
public interface Entrance {

    @WebMethod
    @Action(input = "http://127.0.0.1:8787/Entrance/Entrance/getDataRequest", output = "http://127.0.0.1:8787/Entrance/Entrance/getDataResponse")
    @RequestWrapper(localName = "getData", targetNamespace = "http://127.0.0.1:8787/Entrance", className = "com.jxjr.ynzw.client.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://127.0.0.1:8787/Entrance", className = "com.jxjr.ynzw.client.GetDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getData(
        @WebParam(name = "data", targetNamespace = "")
        java.lang.String data
    );

    @WebMethod
    @Action(input = "http://127.0.0.1:8787/Entrance/Entrance/getTextRequest", output = "http://127.0.0.1:8787/Entrance/Entrance/getTextResponse")
    @RequestWrapper(localName = "getText", targetNamespace = "http://127.0.0.1:8787/Entrance", className = "com.jxjr.ynzw.client.GetText")
    @ResponseWrapper(localName = "getTextResponse", targetNamespace = "http://127.0.0.1:8787/Entrance", className = "com.jxjr.ynzw.client.GetTextResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getText(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );
}
