package com.jxjr.ynzw.fclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-23T11:44:13.228+08:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "FileServiceImpService",
                  wsdlLocation = "http://127.0.0.1:8787/FileService?wsdl",
                  targetNamespace = "http://app.ynzw.jxjr.com/")
public class FileServiceImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://app.ynzw.jxjr.com/", "FileServiceImpService");
    public final static QName FileServiceImpPort = new QName("http://app.ynzw.jxjr.com/", "FileServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8787/FileService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FileServiceImpService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8787/FileService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FileServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FileServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileServiceImpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FileServiceImpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FileServiceImpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FileServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FileService
     */
    @WebEndpoint(name = "FileServiceImpPort")
    public FileService getFileServiceImpPort() {
        return super.getPort(FileServiceImpPort, FileService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileService
     */
    @WebEndpoint(name = "FileServiceImpPort")
    public FileService getFileServiceImpPort(WebServiceFeature... features) {
        return super.getPort(FileServiceImpPort, FileService.class, features);
    }

}
