package com.jxjr.ynzw.fclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-23T11:44:13.148+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://127.0.0.1:8787/FileService", name = "FileService")
@XmlSeeAlso({ObjectFactory.class})
public interface FileService {

    @WebMethod
    @Action(input = "http://127.0.0.1:8787/FileService/FileService/downloadRequest", output = "http://127.0.0.1:8787/FileService/FileService/downloadResponse")
    @RequestWrapper(localName = "download", targetNamespace = "http://127.0.0.1:8787/FileService", className = "com.jxjr.ynzw.fclient.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://127.0.0.1:8787/FileService", className = "com.jxjr.ynzw.fclient.DownloadResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.jxjr.ynzw.fclient.FileWraper download(
        @WebParam(name = "filename", targetNamespace = "")
        java.lang.String filename
    );

    @WebMethod
    @Action(input = "http://127.0.0.1:8787/FileService/FileService/uploadRequest", output = "http://127.0.0.1:8787/FileService/FileService/uploadResponse")
    @RequestWrapper(localName = "upload", targetNamespace = "http://127.0.0.1:8787/FileService", className = "com.jxjr.ynzw.fclient.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://127.0.0.1:8787/FileService", className = "com.jxjr.ynzw.fclient.UploadResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean upload(
        @WebParam(name = "file", targetNamespace = "")
        com.jxjr.ynzw.fclient.FileWraper file
    );
}
